name: Publish Docker Image

on:
  push:
    branches: [main]

jobs:
  ghcr:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ghcr.io/${{ github.repository }}:latest

  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        if: vars.DOCKER_USERNAME != null
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: vars.DOCKER_USERNAME != null
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: vars.DOCKER_USERNAME != null
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to Docker Hub
        if: vars.DOCKER_USERNAME != null
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        if: vars.DOCKER_USERNAME != null
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ github.repository }}:latest
