name: Publish TalkOps Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  ghcr:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Extract tag without 'v'
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }}
            ghcr.io/${{ github.repository }}:latest

      - name: Notify Webhook
        run: |
          curl -X POST https://af56d2b1.talkops.app \
            -H "Content-Type: application/json" \
            -d '{"repository": "${{ github.repository }}", "tag": "${{ env.TAG_NAME }}"}'
